environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"

install:
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisdk.msi'
  - msmpisdk.msi /passive

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: cmake --build . --config release