name: ci
on: [push]
jobs:
  mac-os-build:
    runs-on: macos-latest
    run: brew update-reset;
    run: brew install open-mpi;
    run: mkdir build && cd build
    run: cmake ..
    run: cmake --build . --config release -- -j4