name: ci
on: [push, pull_request]
jobs:
  mac-os-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew update-reset;
      - run: brew install open-mpi;
      - run: mkdir build
      - working-directory: build
        run: cmake ..
      - working-directory: build
        run: cmake --build . --config release -- -j4
